name: The Little Things We Miss
url: http://thelittlethingswemiss.us
baseurl: 
title: The Little Things We Miss
description: Photography by William Raymond Clark of the Little Things We Miss

theme: jekyll-theme-midnight
show_downloads: false

collections:
  aurii_library:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: titled
  - scope:
      path: "_posts/galleries"
      type: posts
    values:
      layout: gallery
  - scope:
      path: "indexes"
    values:
      layout: titled

flickr:
  cache_dir: "./_cache/flickr"
  api_key: 6b3911916a3253512d800718fb1d088b
  shared_secret: 4b1f75ac49facdc2
  access_token: 72157686481612465-4a910c3f2740549d
  access_secret: 5394c7951808871d

google_analytics: UA-109921332-1

plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-seo-tag


pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
